#!/bin/bash

# Setup script to create the legacy kernel source tree which the Love book
# is based on and a modern tag for comparison. The 2.6.34 kernel does not build
# on Debian 12, even with kbuild toolchains, since there is a dependance upon the
# libmpfr.so.4 that Debian no longers ships with (and probably other dependacies
# as well). If I ever get to the point I want to rebuild the older kernel, a
# CentOS 6 virtual machine is probably the only way to do it).

kernel_url="https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
kernel_legacy_tag="v2.6.34"
kernel_modern_tag="v6.18"

function err () {
    local msg
    msg="${1}"
    builtin printf 'Error: %s\n' "${msg}" >&2
}

# Get the legacy kernel
if ! git clone --depth 1 --branch "${kernel_legacy_tag}" "${kernel_url}" "linux-${kernel_legacy_tag}"; then
    err "unable to clone ${kernel_url} at tag ${kernel_legacy_tag}"
    exit 1
fi

# Get the modern kernel
if ! git clone --depth 1 --branch "${kernel_modern_tag}" "${kernel_url}" "linux-${kernel_modern_tag}"; then
    err "unable to clone ${kernel_url} at tag ${kernel_modern_tag}"
    exit 1
fi

